# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-01 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(max_length=200)),
                ('subcategory', models.CharField(blank=True, max_length=200)),
                ('parent', models.CharField(blank=True, max_length=100)),
            ]
        )
    ]
