# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['category', 'subcategory', 'tag_name']},
        ),
    ]
