# Generated by Django 4.2 on 2023-10-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_auto_20190501_1846"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
