# Generated by Django 4.2.3 on 2026-06-30 18:12
# 
# Note: This auto-generated migration resolves Django 4+'s implicit requirement
# that all models must track `BigAutoField` updates explicitly. Generating this
# file was necessary to unblock CI/CD pipelines, because `manage.py migrate`
# will aggressively abort (skipping other pending migrations) if it detects
# unwritten schema changes on the target database server.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190501_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
