// @flow
import type { Dictionary } from "../types/Generics";

export type CountryCodeFormat = "ISO_2" | "ISO_3";

export const CountryCodeFormats: Dictionary<CountryCodeFormat> = {
  ISO_2: "ISO_2",
  ISO_3: "ISO_3",
};

export type CountryData = {|
  displayName: string,
  ISO_2: string,
  ISO_3: string,
|};

export function countryByCode(code: string): ?CountryData {
  if (code) {
    const codeFormat: CountryCodeFormat = "ISO_" + code.length;
    return CountryList.find(
      (country: CountryData) => country[codeFormat] === code
    );
  }
}

export const CountryList: $ReadOnlyArray<CountryData> = [
  { displayName: 'Afghanistan', ISO_2: 'AF', ISO_3: 'AFG' },
  { displayName: 'Aland Islands', ISO_2: 'AX', ISO_3: 'ALA' },
  { displayName: 'Albania', ISO_2: 'AL', ISO_3: 'ALB' },
  { displayName: 'Algeria', ISO_2: 'DZ', ISO_3: 'DZA' },
  { displayName: 'American Samoa', ISO_2: 'AS', ISO_3: 'ASM' },
  { displayName: 'Andorra', ISO_2: 'AD', ISO_3: 'AND' },
  { displayName: 'Angola', ISO_2: 'AO', ISO_3: 'AGO' },
  { displayName: 'Anguilla', ISO_2: 'AI', ISO_3: 'AIA' },
  { displayName: 'Antarctica', ISO_2: 'AQ', ISO_3: 'ATA' },
  { displayName: 'Antigua and Barbuda', ISO_2: 'AG', ISO_3: 'ATG' },
  { displayName: 'Argentina', ISO_2: 'AR', ISO_3: 'ARG' },
  { displayName: 'Armenia', ISO_2: 'AM', ISO_3: 'ARM' },
  { displayName: 'Aruba', ISO_2: 'AW', ISO_3: 'ABW' },
  { displayName: 'Australia', ISO_2: 'AU', ISO_3: 'AUS' },
  { displayName: 'Austria', ISO_2: 'AT', ISO_3: 'AUT' },
  { displayName: 'Azerbaijan', ISO_2: 'AZ', ISO_3: 'AZE' },
  { displayName: 'Bahamas', ISO_2: 'BS', ISO_3: 'BHS' },
  { displayName: 'Bahrain', ISO_2: 'BH', ISO_3: 'BHR' },
  { displayName: 'Bangladesh', ISO_2: 'BD', ISO_3: 'BGD' },
  { displayName: 'Barbados', ISO_2: 'BB', ISO_3: 'BRB' },
  { displayName: 'Belarus', ISO_2: 'BY', ISO_3: 'BLR' },
  { displayName: 'Belgium', ISO_2: 'BE', ISO_3: 'BEL' },
  { displayName: 'Belize', ISO_2: 'BZ', ISO_3: 'BLZ' },
  { displayName: 'Benin', ISO_2: 'BJ', ISO_3: 'BEN' },
  { displayName: 'Bermuda', ISO_2: 'BM', ISO_3: 'BMU' },
  { displayName: 'Bhutan', ISO_2: 'BT', ISO_3: 'BTN' },
  { displayName: 'Bolivia', ISO_2: 'BO', ISO_3: 'BOL' },
  { displayName: 'Bonaire, Sint Eustatius and Saba', ISO_2: 'BQ', ISO_3: 'BES' },
  { displayName: 'Bosnia and Herzegovina', ISO_2: 'BA', ISO_3: 'BIH' },
  { displayName: 'Botswana', ISO_2: 'BW', ISO_3: 'BWA' },
  { displayName: 'Bouvet Island', ISO_2: 'BV', ISO_3: 'BVT' },
  { displayName: 'Brazil', ISO_2: 'BR', ISO_3: 'BRA' },
  { displayName: 'British Indian Ocean Territory', ISO_2: 'IO', ISO_3: 'IOT' },
  { displayName: 'British Virgin Islands', ISO_2: 'VG', ISO_3: 'VGB' },
  { displayName: 'Brunei', ISO_2: 'BN', ISO_3: 'BRN' },
  { displayName: 'Bulgaria', ISO_2: 'BG', ISO_3: 'BGR' },
  { displayName: 'Burkina Faso', ISO_2: 'BF', ISO_3: 'BFA' },
  { displayName: 'Burundi', ISO_2: 'BI', ISO_3: 'BDI' },
  { displayName: 'Cambodia', ISO_2: 'KH', ISO_3: 'KHM' },
  { displayName: 'Cameroon', ISO_2: 'CM', ISO_3: 'CMR' },
  { displayName: 'Canada', ISO_2: 'CA', ISO_3: 'CAN' },
  { displayName: 'Cape Verde', ISO_2: 'CV', ISO_3: 'CPV' },
  { displayName: 'Cayman Islands', ISO_2: 'KY', ISO_3: 'CYM' },
  { displayName: 'Central African Republic', ISO_2: 'CF', ISO_3: 'CAF' },
  { displayName: 'Chad', ISO_2: 'TD', ISO_3: 'TCD' },
  { displayName: 'Chile', ISO_2: 'CL', ISO_3: 'CHL' },
  { displayName: 'China', ISO_2: 'CN', ISO_3: 'CHN' },
  { displayName: 'Christmas Island', ISO_2: 'CX', ISO_3: 'CXR' },
  { displayName: 'Cocos (Keeling) Islands', ISO_2: 'CC', ISO_3: 'CCK' },
  { displayName: 'Colombia', ISO_2: 'CO', ISO_3: 'COL' },
  { displayName: 'Comoros', ISO_2: 'KM', ISO_3: 'COM' },
  { displayName: 'Congo', ISO_2: 'CD', ISO_3: 'COD' },
  { displayName: 'Congo (Brazzaville)', ISO_2: 'CG', ISO_3: 'COG' },
  { displayName: 'Cook Islands', ISO_2: 'CK', ISO_3: 'COK' },
  { displayName: 'Costa Rica', ISO_2: 'CR', ISO_3: 'CRI' },
  { displayName: 'Croatia', ISO_2: 'HR', ISO_3: 'HRV' },
  { displayName: 'Cuba', ISO_2: 'CU', ISO_3: 'CUB' },
  { displayName: 'Curaçao', ISO_2: 'CW', ISO_3: 'CUW' },
  { displayName: 'Cyprus', ISO_2: 'CY', ISO_3: 'CYP' },
  { displayName: 'Czech Republic', ISO_2: 'CZ', ISO_3: 'CZE' },
  { displayName: "Côte d'Ivoire", ISO_2: 'CI', ISO_3: 'CIV' },
  { displayName: 'Denmark', ISO_2: 'DK', ISO_3: 'DNK' },
  { displayName: 'Djibouti', ISO_2: 'DJ', ISO_3: 'DJI' },
  { displayName: 'Dominica', ISO_2: 'DM', ISO_3: 'DMA' },
  { displayName: 'Dominican Republic', ISO_2: 'DO', ISO_3: 'DOM' },
  { displayName: 'Ecuador', ISO_2: 'EC', ISO_3: 'ECU' },
  { displayName: 'Egypt', ISO_2: 'EG', ISO_3: 'EGY' },
  { displayName: 'El Salvador', ISO_2: 'SV', ISO_3: 'SLV' },
  { displayName: 'Equatorial Guinea', ISO_2: 'GQ', ISO_3: 'GNQ' },
  { displayName: 'Eritrea', ISO_2: 'ER', ISO_3: 'ERI' },
  { displayName: 'Estonia', ISO_2: 'EE', ISO_3: 'EST' },
  { displayName: 'Ethiopia', ISO_2: 'ET', ISO_3: 'ETH' },
  { displayName: 'Falkland Islands', ISO_2: 'FK', ISO_3: 'FLK' },
  { displayName: 'Faroe Islands', ISO_2: 'FO', ISO_3: 'FRO' },
  { displayName: 'Fiji', ISO_2: 'FJ', ISO_3: 'FJI' },
  { displayName: 'Finland', ISO_2: 'FI', ISO_3: 'FIN' },
  { displayName: 'France', ISO_2: 'FR', ISO_3: 'FRA' },
  { displayName: 'French Guiana', ISO_2: 'GF', ISO_3: 'GUF' },
  { displayName: 'French Polynesia', ISO_2: 'PF', ISO_3: 'PYF' },
  { displayName: 'French Southern Territories', ISO_2: 'TF', ISO_3: 'ATF' },
  { displayName: 'Gabon', ISO_2: 'GA', ISO_3: 'GAB' },
  { displayName: 'Gambia', ISO_2: 'GM', ISO_3: 'GMB' },
  { displayName: 'Georgia', ISO_2: 'GE', ISO_3: 'GEO' },
  { displayName: 'Germany', ISO_2: 'DE', ISO_3: 'DEU' },
  { displayName: 'Ghana', ISO_2: 'GH', ISO_3: 'GHA' },
  { displayName: 'Gibraltar', ISO_2: 'GI', ISO_3: 'GIB' },
  { displayName: 'Greece', ISO_2: 'GR', ISO_3: 'GRC' },
  { displayName: 'Greenland', ISO_2: 'GL', ISO_3: 'GRL' },
  { displayName: 'Grenada', ISO_2: 'GD', ISO_3: 'GRD' },
  { displayName: 'Guadeloupe', ISO_2: 'GP', ISO_3: 'GLP' },
  { displayName: 'Guam', ISO_2: 'GU', ISO_3: 'GUM' },
  { displayName: 'Guatemala', ISO_2: 'GT', ISO_3: 'GTM' },
  { displayName: 'Guernsey', ISO_2: 'GG', ISO_3: 'GGY' },
  { displayName: 'Guinea', ISO_2: 'GN', ISO_3: 'GIN' },
  { displayName: 'Guinea-Bissau', ISO_2: 'GW', ISO_3: 'GNB' },
  { displayName: 'Guyana', ISO_2: 'GY', ISO_3: 'GUY' },
  { displayName: 'Haiti', ISO_2: 'HT', ISO_3: 'HTI' },
  { displayName: 'Heard and Mcdonald Islands', ISO_2: 'HM', ISO_3: 'HMD' },
  { displayName: 'Honduras', ISO_2: 'HN', ISO_3: 'HND' },
  { displayName: 'Hong Kong', ISO_2: 'HK', ISO_3: 'HKG' },
  { displayName: 'Hungary', ISO_2: 'HU', ISO_3: 'HUN' },
  { displayName: 'Iceland', ISO_2: 'IS', ISO_3: 'ISL' },
  { displayName: 'India', ISO_2: 'IN', ISO_3: 'IND' },
  { displayName: 'Indonesia', ISO_2: 'ID', ISO_3: 'IDN' },
  { displayName: 'Iran', ISO_2: 'IR', ISO_3: 'IRN' },
  { displayName: 'Iraq', ISO_2: 'IQ', ISO_3: 'IRQ' },
  { displayName: 'Ireland', ISO_2: 'IE', ISO_3: 'IRL' },
  { displayName: 'Isle of Man', ISO_2: 'IM', ISO_3: 'IMN' },
  { displayName: 'Israel', ISO_2: 'IL', ISO_3: 'ISR' },
  { displayName: 'Italy', ISO_2: 'IT', ISO_3: 'ITA' },
  { displayName: 'Jamaica', ISO_2: 'JM', ISO_3: 'JAM' },
  { displayName: 'Japan', ISO_2: 'JP', ISO_3: 'JPN' },
  { displayName: 'Jersey', ISO_2: 'JE', ISO_3: 'JEY' },
  { displayName: 'Jordan', ISO_2: 'JO', ISO_3: 'JOR' },
  { displayName: 'Kazakhstan', ISO_2: 'KZ', ISO_3: 'KAZ' },
  { displayName: 'Kenya', ISO_2: 'KE', ISO_3: 'KEN' },
  { displayName: 'Kiribati', ISO_2: 'KI', ISO_3: 'KIR' },
  { displayName: 'Korea (North)', ISO_2: 'KP', ISO_3: 'PRK' },
  { displayName: 'Korea (South)', ISO_2: 'KR', ISO_3: 'KOR' },
  { displayName: 'Kuwait', ISO_2: 'KW', ISO_3: 'KWT' },
  { displayName: 'Kyrgyzstan', ISO_2: 'KG', ISO_3: 'KGZ' },
  { displayName: 'Lao PDR', ISO_2: 'LA', ISO_3: 'LAO' },
  { displayName: 'Latvia', ISO_2: 'LV', ISO_3: 'LVA' },
  { displayName: 'Lebanon', ISO_2: 'LB', ISO_3: 'LBN' },
  { displayName: 'Lesotho', ISO_2: 'LS', ISO_3: 'LSO' },
  { displayName: 'Liberia', ISO_2: 'LR', ISO_3: 'LBR' },
  { displayName: 'Libya', ISO_2: 'LY', ISO_3: 'LBY' },
  { displayName: 'Liechtenstein', ISO_2: 'LI', ISO_3: 'LIE' },
  { displayName: 'Lithuania', ISO_2: 'LT', ISO_3: 'LTU' },
  { displayName: 'Luxembourg', ISO_2: 'LU', ISO_3: 'LUX' },
  { displayName: 'Macao', ISO_2: 'MO', ISO_3: 'MAC' },
  { displayName: 'Macedonia', ISO_2: 'MK', ISO_3: 'MKD' },
  { displayName: 'Madagascar', ISO_2: 'MG', ISO_3: 'MDG' },
  { displayName: 'Malawi', ISO_2: 'MW', ISO_3: 'MWI' },
  { displayName: 'Malaysia', ISO_2: 'MY', ISO_3: 'MYS' },
  { displayName: 'Maldives', ISO_2: 'MV', ISO_3: 'MDV' },
  { displayName: 'Mali', ISO_2: 'ML', ISO_3: 'MLI' },
  { displayName: 'Malta', ISO_2: 'MT', ISO_3: 'MLT' },
  { displayName: 'Marshall Islands', ISO_2: 'MH', ISO_3: 'MHL' },
  { displayName: 'Martinique', ISO_2: 'MQ', ISO_3: 'MTQ' },
  { displayName: 'Mauritania', ISO_2: 'MR', ISO_3: 'MRT' },
  { displayName: 'Mauritius', ISO_2: 'MU', ISO_3: 'MUS' },
  { displayName: 'Mayotte', ISO_2: 'YT', ISO_3: 'MYT' },
  { displayName: 'Mexico', ISO_2: 'MX', ISO_3: 'MEX' },
  { displayName: 'Micronesia', ISO_2: 'FM', ISO_3: 'FSM' },
  { displayName: 'Moldova', ISO_2: 'MD', ISO_3: 'MDA' },
  { displayName: 'Monaco', ISO_2: 'MC', ISO_3: 'MCO' },
  { displayName: 'Mongolia', ISO_2: 'MN', ISO_3: 'MNG' },
  { displayName: 'Montenegro', ISO_2: 'ME', ISO_3: 'MNE' },
  { displayName: 'Montserrat', ISO_2: 'MS', ISO_3: 'MSR' },
  { displayName: 'Morocco', ISO_2: 'MA', ISO_3: 'MAR' },
  { displayName: 'Mozambique', ISO_2: 'MZ', ISO_3: 'MOZ' },
  { displayName: 'Myanmar', ISO_2: 'MM', ISO_3: 'MMR' },
  { displayName: 'Namibia', ISO_2: 'NA', ISO_3: 'NAM' },
  { displayName: 'Nauru', ISO_2: 'NR', ISO_3: 'NRU' },
  { displayName: 'Nepal', ISO_2: 'NP', ISO_3: 'NPL' },
  { displayName: 'Netherlands', ISO_2: 'NL', ISO_3: 'NLD' },
  { displayName: 'Netherlands Antilles', ISO_2: 'AN', ISO_3: 'ANT' },
  { displayName: 'New Caledonia', ISO_2: 'NC', ISO_3: 'NCL' },
  { displayName: 'New Zealand', ISO_2: 'NZ', ISO_3: 'NZL' },
  { displayName: 'Nicaragua', ISO_2: 'NI', ISO_3: 'NIC' },
  { displayName: 'Niger', ISO_2: 'NE', ISO_3: 'NER' },
  { displayName: 'Nigeria', ISO_2: 'NG', ISO_3: 'NGA' },
  { displayName: 'Niue', ISO_2: 'NU', ISO_3: 'NIU' },
  { displayName: 'Norfolk Island', ISO_2: 'NF', ISO_3: 'NFK' },
  { displayName: 'Northern Mariana Islands', ISO_2: 'MP', ISO_3: 'MNP'},
  { displayName: 'Norway', ISO_2: 'NO', ISO_3: 'NOR' },
  { displayName: 'Oman', ISO_2: 'OM', ISO_3: 'OMN' },
  { displayName: 'Pakistan', ISO_2: 'PK', ISO_3: 'PAK' },
  { displayName: 'Palau', ISO_2: 'PW', ISO_3: 'PLW' },
  { displayName: 'Palestinian Territory', ISO_2: 'PS', ISO_3: 'PSE' },
  { displayName: 'Panama', ISO_2: 'PA', ISO_3: 'PAN' },
  { displayName: 'Papua New Guinea', ISO_2: 'PG', ISO_3: 'PNG' },
  { displayName: 'Paraguay', ISO_2: 'PY', ISO_3: 'PRY' },
  { displayName: 'Peru', ISO_2: 'PE', ISO_3: 'PER' },
  { displayName: 'Philippines', ISO_2: 'PH', ISO_3: 'PHL' },
  { displayName: 'Pitcairn', ISO_2: 'PN', ISO_3: 'PCN' },
  { displayName: 'Poland', ISO_2: 'PL', ISO_3: 'POL' },
  { displayName: 'Portugal', ISO_2: 'PT', ISO_3: 'PRT' },
  { displayName: 'Puerto Rico', ISO_2: 'PR', ISO_3: 'PRI' },
  { displayName: 'Qatar', ISO_2: 'QA', ISO_3: 'QAT' },
  { displayName: 'Romania', ISO_2: 'RO', ISO_3: 'ROU' },
  { displayName: 'Russian Federation', ISO_2: 'RU', ISO_3: 'RUS' },
  { displayName: 'Rwanda', ISO_2: 'RW', ISO_3: 'RWA' },
  { displayName: 'Réunion', ISO_2: 'RE', ISO_3: 'REU' },
  { displayName: 'Saint Helena', ISO_2: 'SH', ISO_3: 'SHN' },
  { displayName: 'Saint Kitts and Nevis', ISO_2: 'KN', ISO_3: 'KNA' },
  { displayName: 'Saint Lucia', ISO_2: 'LC', ISO_3: 'LCA' },
  { displayName: 'Saint Pierre and Miquelon', ISO_2: 'PM', ISO_3: 'SPM' },
  { displayName: 'Saint Vincent and Grenadines', ISO_2: 'VC',ISO_3: 'VCT' },
  { displayName: 'Saint-Barthélemy', ISO_2: 'BL', ISO_3: 'BLM' },
  { displayName: 'Saint-Martin (French part)', ISO_2: 'MF', ISO_3: 'MAF' },
  { displayName: 'Samoa', ISO_2: 'WS', ISO_3: 'WSM' },
  { displayName: 'San Marino', ISO_2: 'SM', ISO_3: 'SMR' },
  { displayName: 'Sao Tome and Principe', ISO_2: 'ST', ISO_3: 'STP' },
  { displayName: 'Saudi Arabia', ISO_2: 'SA', ISO_3: 'SAU' },
  { displayName: 'Senegal', ISO_2: 'SN', ISO_3: 'SEN' },
  { displayName: 'Serbia', ISO_2: 'RS', ISO_3: 'SRB' },
  { displayName: 'Seychelles', ISO_2: 'SC', ISO_3: 'SYC' },
  { displayName: 'Sierra Leone', ISO_2: 'SL', ISO_3: 'SLE' },
  { displayName: 'Singapore', ISO_2: 'SG', ISO_3: 'SGP' },
  { displayName: 'Sint Maarten (Dutch part)', ISO_2: 'SX', ISO_3: 'SXM' },
  { displayName: 'Slovakia', ISO_2: 'SK', ISO_3: 'SVK' },
  { displayName: 'Slovenia', ISO_2: 'SI', ISO_3: 'SVN' },
  { displayName: 'Solomon Islands', ISO_2: 'SB', ISO_3: 'SLB' },
  { displayName: 'Somalia', ISO_2: 'SO', ISO_3: 'SOM' },
  { displayName: 'South Africa', ISO_2: 'ZA', ISO_3: 'ZAF' },
  { displayName: 'South Georgia and the South Sandwich Islands', ISO_2: 'GS', ISO_3: 'SGS' },
  { displayName: 'South Sudan', ISO_2: 'SS', ISO_3: 'SSD' },
  { displayName: 'Spain', ISO_2: 'ES', ISO_3: 'ESP' },
  { displayName: 'Sri Lanka', ISO_2: 'LK', ISO_3: 'LKA' },
  { displayName: 'Sudan', ISO_2: 'SD', ISO_3: 'SDN' },
  { displayName: 'Suriname', ISO_2: 'SR', ISO_3: 'SUR' },
  { displayName: 'Svalbard and Jan Mayen Islands', ISO_2: 'SJ', ISO_3: 'SJM' },
  { displayName: 'Swaziland', ISO_2: 'SZ', ISO_3: 'SWZ' },
  { displayName: 'Sweden', ISO_2: 'SE', ISO_3: 'SWE' },
  { displayName: 'Switzerland', ISO_2: 'CH', ISO_3: 'CHE' },
  { displayName: 'Syria', ISO_2: 'SY', ISO_3: 'SYR' },
  { displayName: 'Taiwan', ISO_2: 'TW', ISO_3: 'TWN' },
  { displayName: 'Tajikistan', ISO_2: 'TJ', ISO_3: 'TJK' },
  { displayName: 'Tanzania', ISO_2: 'TZ', ISO_3: 'TZA' },
  { displayName: 'Thailand', ISO_2: 'TH', ISO_3: 'THA' },
  { displayName: 'Timor-Leste', ISO_2: 'TL', ISO_3: 'TLS' },
  { displayName: 'Togo', ISO_2: 'TG', ISO_3: 'TGO' },
  { displayName: 'Tokelau', ISO_2: 'TK', ISO_3: 'TKL' },
  { displayName: 'Tonga', ISO_2: 'TO', ISO_3: 'TON' },
  { displayName: 'Trinidad and Tobago', ISO_2: 'TT', ISO_3: 'TTO' },
  { displayName: 'Tunisia', ISO_2: 'TN', ISO_3: 'TUN' },
  { displayName: 'Turkey', ISO_2: 'TR', ISO_3: 'TUR' },
  { displayName: 'Turkmenistan', ISO_2: 'TM', ISO_3: 'TKM' },
  { displayName: 'Turks and Caicos Islands', ISO_2: 'TC', ISO_3: 'TCA' },
  { displayName: 'Tuvalu', ISO_2: 'TV', ISO_3: 'TUV' },
  { displayName: 'US Minor Outlying Islands', ISO_2: 'UM', ISO_3: 'UMI' },
  { displayName: 'Uganda', ISO_2: 'UG', ISO_3: 'UGA' },
  { displayName: 'Ukraine', ISO_2: 'UA', ISO_3: 'UKR' },
  { displayName: 'United Arab Emirates', ISO_2: 'AE', ISO_3: 'ARE' },
  { displayName: 'United Kingdom', ISO_2: 'GB', ISO_3: 'GBR' },
  { displayName: 'United States of America', ISO_2: 'US', ISO_3: 'USA' },
  { displayName: 'Uruguay', ISO_2: 'UY', ISO_3: 'URY' },
  { displayName: 'Uzbekistan', ISO_2: 'UZ', ISO_3: 'UZB' },
  { displayName: 'Vanuatu', ISO_2: 'VU', ISO_3: 'VUT' },
  { displayName: 'Vatican City', ISO_2: 'VA', ISO_3: 'VAT' },
  { displayName: 'Venezuela', ISO_2: 'VE', ISO_3: 'VEN' },
  { displayName: 'Vietnam', ISO_2: 'VN', ISO_3: 'VNM' },
  { displayName: 'Virgin Islands', ISO_2: 'VI', ISO_3: 'VIR' },
  { displayName: 'Wallis and Futuna Islands', ISO_2: 'WF', ISO_3: 'WLF' },
  { displayName: 'Western Sahara', ISO_2: 'EH', ISO_3: 'ESH' },
  { displayName: 'Yemen', ISO_2: 'YE', ISO_3: 'YEM' },
  { displayName: 'Zambia', ISO_2: 'ZM', ISO_3: 'ZMB' },
  { displayName: 'Zimbabwe', ISO_2: 'ZW', ISO_3: 'ZWE' }
];

export const DefaultCountry: CountryData = countryByCode("USA");
