# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-06 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('democracylab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_url', models.CharField(blank=True, max_length=200)),
                ('project_description', models.CharField(blank=True, max_length=1000)),
                ('project_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='democracylab.Contributor')),
                ('project_tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
