# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-01 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('democracylab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_url', models.CharField(blank=True, max_length=200)),
                ('project_description', models.CharField(blank=True, max_length=1000)),
                ('project_tags', models.CharField(blank=True, max_length=1000)),
                ('project_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='democracylab.Contributor')),
            ],
        ),
    ]
