# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-21 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('democracylab', '0001_initial'),
        ('civictechprojects', '0003_auto_20171125_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_volunteers',
            field=models.ManyToManyField(related_name='volunteers', to='democracylab.Contributor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='democracylab.Contributor'),
        ),
    ]
