# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-04 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0004_auto_20171221_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_visibility', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=200)),
                ('file_key', models.CharField(max_length=200)),
                ('file_url', models.CharField(max_length=2000)),
                ('file_type', models.CharField(max_length=50)),
                ('file_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(blank=True, max_length=200)),
                ('link_url', models.CharField(max_length=2000)),
                ('link_visibility', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_links',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='projectlink',
            name='link_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='civictechprojects.Project'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='file_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='civictechprojects.Project'),
        ),
    ]
