# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-22 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0005_auto_20180104_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.CharField(blank=True, max_length=2083),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file_url',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='projectlink',
            name='link_url',
            field=models.CharField(max_length=2083),
        ),
    ]
