# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-17 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0006_auto_20180122_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedtag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedtag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_tags',
        ),
        migrations.DeleteModel(
            name='TaggedTag',
        ),
    ]
