# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-22 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0009_auto_20180403_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_searchable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_volunteers',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='democracylab.Contributor'),
        ),
    ]
