# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-29 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0010_auto_20180522_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectposition',
            name='description_url',
            field=models.CharField(default='', max_length=2083),
        ),
        migrations.AlterField(
            model_name='projectposition',
            name='position_description',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
