# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-26 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('civictechprojects', '0011_auto_20180529_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civictechprojects.Project')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civictechprojects_taggedorganization_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_organization',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='civictechprojects.TaggedOrganization', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
