# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-30 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('democracylab', '0003_auto_20180911_0124'),
        ('civictechprojects', '0016_auto_20180911_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedVolunteerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_text', models.CharField(blank=True, max_length=10000)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_volunteers',
        ),
        migrations.AddField(
            model_name='volunteerrelation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='civictechprojects.Project'),
        ),
        migrations.AddField(
            model_name='volunteerrelation',
            name='role',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='civictechprojects.TaggedVolunteerRole', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='volunteerrelation',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='democracylab.Contributor'),
        ),
        migrations.AddField(
            model_name='taggedvolunteerrole',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civictechprojects.VolunteerRelation'),
        ),
        migrations.AddField(
            model_name='taggedvolunteerrole',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civictechprojects_taggedvolunteerrole_items', to='taggit.Tag'),
        ),
    ]
