# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-05 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0019_project_project_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerrelation',
            name='is_co_owner',
            field=models.BooleanField(default=False),
        ),
    ]
