# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-17 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0024_auto_20190326_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Archive',
            fields=[
                ('id', models.IntegerField(primary_key=True, auto_created=False)),
                ('project_name', models.CharField(max_length=200)),
                ('project_creator_id', models.IntegerField()),
                ('project_short_description', models.CharField(blank=True, max_length=140)),
                ('project_description', models.CharField(blank=True, max_length=3000)),
                ('project_location', models.CharField(max_length=200)),
                ('project_url', models.CharField(blank=True, max_length=2083)),
                ('project_links', models.CharField(blank=True, max_length=5000)),
                ('is_searchable', models.BooleanField(default=True)),
                ('project_date_created', models.DateTimeField(null=True)),
                ('project_date_modified', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerRelation_Archive',
            fields=[
                ('id', models.IntegerField(primary_key=True, auto_created=False)),
                ('project_id', models.IntegerField()),
                ('volunteer_id', models.IntegerField()),
                ('is_approved', models.BooleanField(default=False)),
                ('is_co_owner', models.BooleanField(default=False)),
                ('application_text', models.CharField(blank=True, max_length=10000)),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('projected_end_date', models.DateTimeField(blank=True, null=True)),
                ('re_enrolled_last_date', models.DateTimeField(blank=True, null=True)),
                ('last_reminder_date', models.DateTimeField(blank=True, null=True)),
                ('re_enroll_last_reminder_date', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.IntegerField(default=0)),
                ('re_enroll_reminder_count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
