# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-17 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('democracylab', '0003_auto_20180911_0124'),
        ('civictechprojects', '0024_auto_20190326_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_description', models.CharField(blank=True, max_length=3000)),
                ('project_short_description', models.CharField(blank=True, max_length=140)),
                ('project_location', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('project_url', models.CharField(blank=True, max_length=2083)),
                ('project_links', models.CharField(blank=True, max_length=5000)),
                ('project_date_created', models.DateTimeField(null=True)),
                ('project_date_modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_searchable', models.BooleanField(default=True)),
                ('project_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_fk', to='democracylab.Contributor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerRelation_Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_co_owner', models.BooleanField(default=False)),
                ('application_text', models.CharField(blank=True, max_length=10000)),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('projected_end_date', models.DateTimeField(blank=True, null=True)),
                ('re_enrolled_last_date', models.DateTimeField(blank=True, null=True)),
                ('last_reminder_date', models.DateTimeField(blank=True, null=True)),
                ('re_enroll_last_reminder_date', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.IntegerField(default=0)),
                ('re_enroll_reminder_count', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_fk', to='civictechprojects.Project')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_fk', to='democracylab.Contributor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
