# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0025_add_field_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_searchable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
