# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-17 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('civictechprojects', '0026_auto_20190522_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedOrganizationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_links',
        ),
        migrations.AddField(
            model_name='project',
            name='is_created',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_description_actions',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='project',
            name='project_description_solution',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='taggedorganizationtype',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civictechprojects.Project'),
        ),
        migrations.AddField(
            model_name='taggedorganizationtype',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civictechprojects_taggedorganizationtype_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_organization_type',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='civictechprojects.TaggedOrganizationType', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
