# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-25 15:44
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0029_projectcommit'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_location_coords',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default='', null=True, srid=4326),
        ),
    ]
