# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-06 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0030_auto_20200501_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_live_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
