# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-07 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('civictechprojects', '0031_event_event_live_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedEventOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civictechprojects.Event')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civictechprojects_taggedeventorganization_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event_legacy_organization',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='civictechprojects.TaggedEventOrganization', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
