# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-02 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0031_auto_20200602_1535'),
        ('civictechprojects', '0032_auto_20200507_1934'),
    ]

    operations = [
    ]
