# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-30 02:20
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0033_merge_20200602_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_location',
        ),
        migrations.AddField(
            model_name='group',
            name='group_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='group',
            name='group_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='group',
            name='group_location_coords',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default='', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='group',
            name='group_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='group',
            name='group_url',
            field=models.CharField(blank=True, max_length=2083),
        ),
    ]
