# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-30 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0034_auto_20200630_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
