# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-08 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0035_group_group_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrelationship',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectrelationship',
            name='project_initiated',
            field=models.BooleanField(default=False),
        ),
    ]
