# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-10 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0037_projectrelationship_introduction_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_organizers_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
