# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-28 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0038_event_event_organizers_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='full_text',
            field=models.CharField(blank=True, max_length=200000),
        ),
    ]
