# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-10-30 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0039_project_full_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_slug',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
