# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-11-25 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0040_auto_20201030_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_slugs', to='civictechprojects.Event')),
            ],
        ),
    ]
