# Generated by Django 3.1.4 on 2021-04-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0043_auto_20210415_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerrelation',
            name='is_team_leader',
            field=models.BooleanField(default=False),
        ),
    ]
