# Generated by Django 3.1.8 on 2021-06-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0045_auto_20210515_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_headers',
            field=models.BooleanField(default=False),
        ),
    ]
