# Generated by Django 3.1.8 on 2021-06-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0046_event_show_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file_name',
            field=models.CharField(max_length=300),
        ),
    ]
