# Generated by Django 3.1.8 on 2021-06-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0047_auto_20210617_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file_key',
            field=models.CharField(max_length=400),
        ),
    ]
