# Generated by Django 3.1.8 on 2021-09-21 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('democracylab', '0009_auto_20210302_2036'),
        ('civictechprojects', '0048_auto_20210618_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='civictechprojects.project')),
                ('link_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='democracylab.contributor')),
            ],
        ),
    ]
