# Generated by Django 3.1.8 on 2021-10-14 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0049_projectfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrelloAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_fullname', models.CharField(max_length=200)),
                ('member_id', models.CharField(max_length=2083)),
                ('board_id', models.CharField(max_length=2083)),
                ('action_type', models.CharField(max_length=2083)),
                ('action_date', models.DateTimeField()),
                ('action_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trello_actions', to='civictechprojects.project')),
            ],
        ),
    ]
