# Generated by Django 3.1.8 on 2021-10-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0050_trelloaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='trelloaction',
            name='member_avatar_base_url',
            field=models.CharField(blank=True, max_length=2083),
        ),
    ]
