# Generated by Django 3.1.8 on 2021-10-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0050_trelloaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trelloaction',
            name='id',
            field=models.CharField(max_length=2083, primary_key=True, serialize=False),
        ),
    ]
