# Generated by Django 3.1.8 on 2021-10-29 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0051_trelloaction_member_avatar_base_url'),
        ('civictechprojects', '0051_auto_20211028_0631'),
    ]

    operations = [
    ]
