# Generated by Django 3.1.8 on 2021-11-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0052_merge_20211029_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='trelloaction',
            name='action_data',
            field=models.JSONField(null=True),
        ),
    ]
