# Generated by Django 3.1.13 on 2022-02-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('democracylab', '0009_auto_20210302_2036'),
        ('civictechprojects', '0054_auto_20211205_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectposition',
            name='position_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='civictechprojects.event'),
        ),
        migrations.CreateModel(
            name='EventProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('goal', models.CharField(blank=True, max_length=2000)),
                ('scope', models.CharField(blank=True, max_length=2000)),
                ('schedule', models.CharField(blank=True, max_length=2000)),
                ('onboarding_notes', models.CharField(blank=True, max_length=2000)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_event_projects', to='democracylab.contributor')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_projects', to='civictechprojects.event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_events', to='civictechprojects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
