# Generated by Django 3.1.13 on 2022-03-24 19:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('democracylab', '0009_auto_20210302_2036'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('civictechprojects', '0056_project_event_created_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVPVolunteerRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('application_text', models.CharField(blank=True, max_length=10000)),
                ('rsvp_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_volunteers', to='civictechprojects.event')),
                ('event_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_volunteers', to='civictechprojects.eventproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedRSVPVolunteerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civictechprojects.rsvpvolunteerrelation')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civictechprojects_taggedrsvpvolunteerrole_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rsvpvolunteerrelation',
            name='role',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='rsvp_roles', through='civictechprojects.TaggedRSVPVolunteerRole', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='rsvpvolunteerrelation',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_events', to='democracylab.contributor'),
        ),
    ]
