# Generated by Django 3.1.13 on 2022-04-14 22:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0057_auto_20220324_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EventConferenceRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(default=0)),
                ('zoom_id', models.BigIntegerField(default=0)),
                ('join_url', models.CharField(max_length=2083)),
                ('admin_url', models.CharField(max_length=2083)),
                ('last_activated', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_rooms', to='civictechprojects.event')),
                ('event_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_conference_rooms', to='civictechprojects.eventproject')),
            ],
        ),
    ]
