# Generated by Django 3.1.14 on 2022-07-13 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0059_eventconferenceroomparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_slug',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='group',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='namerecord',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_slugs', to='civictechprojects.group'),
        ),
        migrations.AddField(
            model_name='namerecord',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_slugs', to='civictechprojects.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='project_slug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
