# Generated by Django 3.1.14 on 2023-01-12 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0061_auto_20221201_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventproject',
            name='event_time_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_zone_event_projects', to='civictechprojects.eventlocationtimezone'),
        ),
    ]
