# Generated by Django 4.2 on 2023-11-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civictechprojects", "0064_dollarssaved_alter_event_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dollarssaved",
            name="dollar_value_impact",
        ),
        migrations.RemoveField(
            model_name="dollarssaved",
            name="total_expenses",
        ),
        migrations.AddField(
            model_name="dollarssaved",
            name="expense",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dollarssaved",
            name="public_value_created",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dollarssaved",
            name="year",
            field=models.DateField(blank=True, null=True),
        ),
    ]
