# Generated by Django 4.2 on 2023-11-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civictechprojects', '0065_remove_dollarssaved_dollar_value_impact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hackathon_count', models.IntegerField(default=0)),
                ('total_hackathon_participants', models.IntegerField(default=0)),
            ],
        ),
    ]
