# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-30 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracylab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
