# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-28 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracylab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='behance',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contributor',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contributor',
            name='dribble',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contributor',
            name='experience_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contributor',
            name='facebook',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contributor',
            name='job_role',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contributor',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contributor',
            name='other_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contributor',
            name='website_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='about_me',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
