# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracylab', '0003_auto_20180911_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='about_me',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
