# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-03 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracylab', '0004_auto_20190429_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='about_me',
            field=models.CharField(blank=True, default='', max_length=100000),
            preserve_default=False,
        ),
    ]
