# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-27 23:36
from __future__ import unicode_literals
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('democracylab', '0006_auto_20200427_2336'),
    ]

    # Don't do this automatically, as this breaks subsequent model changes if not done as the final migration step
    # operations = [migrations.RunPython(backfill_user_uuids)]
