# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-11-06 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracylab', '0007_backfill_user_uuids'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='qiqo_signup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
