# Generated by Django 4.2 on 2023-06-20 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("democracylab", "0009_auto_20210302_2036"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertaggedtechnologies",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_items",
                to="taggit.tag",
            ),
        ),
    ]
