# Generated by Django 4.2.3 on 2026-06-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracylab', '0011_contributor_newsletter_signup_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaggedtechnologies',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
