name: Linting Error Check by Ruff
on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy ruff
    - name: Static type checking with mypy
      run: |
        mypy --python-version 3.8 .
        mypy --python-version 3.9 .
        mypy --python-version 3.10 .
        mypy --python-version 3.11 .
    - name: Run linters
      run: |
        ruff check . --ignore E501 --per-file-ignores __init__.py:F401
