name: Unit Test
on:
  pull_request:
    paths:
      - '**/*.py'
      - '**/*.js'
      - '.github/workflows/unittest.yml'

jobs:
  Run-Unit-Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t civictechexchange-image .

    - name: Run Docker Container Python Test
      run: docker run civictechexchange-image python manager.py test
